import type { GetStaticProps, InferGetStaticPropsType, NextPage } from 'next'
import { getAboutString } from '../src/lib/portfolioHelpers'
import Head from 'next/head'
import Main from '../src/components/portfolio/main'
import NavLinks from '../src/components/portfolio/navlinks'
import Project from '../src/components/portfolio/project'
import Skills from '../src/components/portfolio/skills'
import About from '../src/components/portfolio/about'
import Footer from '../src/components/footer'

const PortfolioPage: NextPage = ({ 
    aboutText,
    projects,
    skills
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <div>
        <Head>
            <title>Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
       
        <Main />
        <About aboutText={aboutText} />
        <Project data={projects} />
        <Skills data={skills}/>
        <Footer />
        <NavLinks />
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
    const { about, skills, projects } = getAboutString()

    return {
        props: {
            aboutText: about,
            skills: skills,
            projects: projects
        }
    }
}

export default PortfolioPage