import type { NextPage } from 'next'
import Head from 'next/head'
import Main from '../src/components/portfolio/main'
import NavLinks from '../src/components/portfolio/navlinks'
import Project from '../src/components/portfolio/project'
import Skills from '../src/components/portfolio/skills'
import About from '../src/components/portfolio/about'
import Footer from '../src/components/footer'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

const Portfolio: NextPage = () => {
  return (
    <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Main />
        <Project />
        <Skills />
        <About />
        <Footer />
        <NavLinks /> 
    </div>
  )
}

export default Portfolio
